// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD87jI03GirppCmAq2FtXVPSs6LTGpXBdo',
    appId: '1:290697532029:web:cb6eba73424b1976cb9714',
    messagingSenderId: '290697532029',
    projectId: 'finalproject-6bfff',
    authDomain: 'finalproject-6bfff.firebaseapp.com',
    storageBucket: 'finalproject-6bfff.appspot.com',
    measurementId: 'G-6NBLNEFHLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWcECf_CtJAtyQiVIwx9P0KLTWb38aUcA',
    appId: '1:290697532029:android:fca28b6dd0213ba4cb9714',
    messagingSenderId: '290697532029',
    projectId: 'finalproject-6bfff',
    storageBucket: 'finalproject-6bfff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVFpVLYcZdrcrINV_4xP9myvoRUDjxGs4',
    appId: '1:290697532029:ios:3dd37159e8108c44cb9714',
    messagingSenderId: '290697532029',
    projectId: 'finalproject-6bfff',
    storageBucket: 'finalproject-6bfff.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVFpVLYcZdrcrINV_4xP9myvoRUDjxGs4',
    appId: '1:290697532029:ios:368dad15208ce79dcb9714',
    messagingSenderId: '290697532029',
    projectId: 'finalproject-6bfff',
    storageBucket: 'finalproject-6bfff.appspot.com',
    iosBundleId: 'com.example.finalproject.RunnerTests',
  );
}
